# Generated by Django 5.2.17 on 2026-09-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='pushed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='stars_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_visible', 'is_featured'], name='proj_vis_feat_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-stars_count', '-pushed_at'], name='proj_stars_pushed_idx'),
        ),
    ]
